services:
  qemu:
    image: qemux/qemu
    container_name: qemu
    environment:
      BOOT: "arch"
      DISK_SIZE: "32G"
      RAM_SIZE: "6G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 2222:22
    volumes:
      - ./qemu:/storage
    restart: always
    stop_grace_period: 2m
