services:
  qemu:
    image: qemux/qemu
    container_name: qemu
    environment:
      BOOT: "https://mirrors.hust.edu.cn/deepin-cd/25.0.1/amd64/deepin-desktop-community-25.0.1-amd64.iso"
      DISK_SIZE: "32G"     
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 2222:22
    volumes:
      - ./qemu:/storage
    restart: always
    stop_grace_period: 2m
